spring.application.name=lolodedefia-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/lolodedefia?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=changeCetteCleSecretePourLaProductionLoloDedefia2026
app.jwt.expiration-ms=604800000
